### ISSUE TITLE
Lifecycle Manager 初始的账号和密码是什么

### ISSUE THREAD

**Issue by houjibofa2050** [FederatedAI/FedLCM#1]
Lifecycle Manager 初始的账号和密码是什么

**Comment by wfangchi** [comment]
Hi! According to https://github.com/FederatedAI/FedLCM/blob/main/doc/Getting_Started_FATE_zh.md:
> 登录口令可以在 docker-compose 的 yaml 文件或者 k8s_deploy yaml 文件中进行配置。默认口令为 Admin:admin。交互界面默认语言为英文，登录成功后可以通过右上角的菜单切换语言。"
